export const langObj = {
  "en": {
    "title": "Anna Khizhniak - Portfolio",
    "name": "Anna Khizhniak",
    "portfolio": "Portfolio",
    "cv": "CV",
    "edu": "Education/Experience",
    "openProject": "Open project",
    "descProjectHobbyart": "flexbox, grid, jquery, java script, swippers, switcher, mobile view, animation",
    "descProjectHillel": "flexbox, jquery, swippers, switcher, mobile view, modal, regexp, form validation",
    "descProjectLocalize": "flexbox, mobile view, jquery",
    "descProjectMeliorit": "flexbox, jquery, swippers, mobile view",
    "descProjectBeauty": "flexbox, jquery, modal, mobile view",
    "descProjectFoxDigital": "flexbox, jquery, java script, swippers, switcher for 2 color schemes, mobile view",
    "descProjectFutureAcademy": "java script, flexbox, grid, bootstrap, swiper, tabs",
  },
  "ru": {
    "title": "Анна Хижняк - Портфолио",
    "name": "Анна Хижняк",
    "portfolio": "Портфолио",
    "cv": "Резюме",
    "edu": "Образование/Опыт",
    "openProject": "Открыть сайт",
    "descProjectHobbyart": "флексбокс, грид, jquery, java script, слайдер, переключатель, анимация, адаптивный дизайн",
    "descProjectHillel": "флексбокс, грид, jquery, java script, слайдер, переключатель, адаптивный дизайн, regexp, валидация форм",
    "descProjectLocalize": "флексбокс, адаптивный дизайн, jquery",
    "descProjectMeliorit": "флексбокс, jquery, слайдер, адаптивный дизайн",
    "descProjectBeauty": "флексбокс, jquery, модальное окно, адаптивный дизайн",
    "descProjectFoxDigital": "флексбокс, jquery, java script, слайдер, переключатель цветовой схемы, адаптивный дизайн",
    "descProjectFutureAcademy": "флексбокс, грид, java script, bootstrap, слайдер, табы",
  },
  "ua": {
    "title": "Анна Хiжняк - Портфолiо",
    "name": "Анна Хiжняк",
    "portfolio": "Портфолiо",
    "cv": "Резюме",
    "edu": "Освіта/Досвід",
    "openProject": "Відкрити сайт",
    "descProjectHobbyart": "флексбокс, грід, jquery, java script, слайдер, перемикач, анімація, адаптивний дизайн",
    "descProjectHillel": "флексбокс, грід, jquery, java script, слайдер, перемикач, адаптивний дизайн, regexp, валідація форм",
    "descProjectLocalize": "флексбокс, адаптивний дизайн, jquery",
    "descProjectMeliorit": "флексбокс, jquery, слайдер, адаптивний дизайн",
    "descProjectBeauty": "флексбокс, jquery, модальне вікно, адаптивний дизайн",
    "descProjectFoxDigital": "флексбокс, jquery, java script, слайдер, перемикач кольору сайту, адаптивний дизайн",
    "descProjectFutureAcademy": "флексбокс, грід, java script, bootstrap, слайдер, таби",
  }
}